# Generated by Django 2.1.7 on 2019-07-14 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_name', models.CharField(max_length=128)),
                ('at_birthday', models.DateField()),
                ('at_deathday', models.DateField()),
                ('at_birthplace', models.CharField(max_length=128)),
                ('at_nationality', models.CharField(max_length=32)),
                ('create_time_tc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录创建时间')),
                ('modify_time_tc', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('remark_tc', models.CharField(max_length=512, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_name', models.CharField(default='', max_length=200, verbose_name='书名')),
                ('bk_author2', models.CharField(default='', max_length=64, verbose_name='作者')),
                ('bk_translator2', models.CharField(default='', max_length=64, null=True, verbose_name='译者')),
                ('bk_page', models.IntegerField(default=0, null=True, verbose_name='页数')),
                ('bk_price', models.IntegerField(default=0, null=True, verbose_name='价格')),
                ('bk_pub_date', models.DateField(null=True, verbose_name='date published')),
                ('bk_ISBN', models.CharField(default='', max_length=16, verbose_name='国际标准书号')),
                ('bk_material', models.CharField(default='', max_length=4, verbose_name='纸质电子')),
                ('bk_category', models.CharField(default='', max_length=4, null=True, verbose_name='图书类型')),
                ('create_time_tc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录创建时间')),
                ('modify_time_tc', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('remark_tc', models.CharField(max_length=512, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='PublishHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_name', models.CharField(default='', max_length=64, verbose_name='出版社')),
                ('ph_founded_date', models.CharField(max_length=64, null=True, verbose_name='成立时间')),
                ('ph_founded_place', models.CharField(max_length=32, null=True, verbose_name='成立时间')),
                ('ph_founder', models.CharField(max_length=128, null=True, verbose_name='创始人')),
                ('ph_headquarter', models.CharField(max_length=128, null=True, verbose_name='总部所在地')),
                ('create_time_tc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录创建时间')),
                ('modify_time_tc', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('remark_tc', models.CharField(max_length=512, null=True, verbose_name='描述')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bk_press',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='libManager.PublishHouse'),
        ),
    ]
