# Generated by Django 2.1.7 on 2019-07-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bk_buy_date',
            field=models.DateTimeField(null=True, verbose_name='购买日期'),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_buy_place',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='购买地点'),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_series',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='所属丛书'),
        ),
    ]
