# Generated by Django 2.1.7 on 2019-07-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManager', '0002_auto_20190721_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bk_press',
        ),
        migrations.AddField(
            model_name='book',
            name='bk_press2',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='book',
            name='bk_subtitle',
            field=models.CharField(default='', max_length=256, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bk_name',
            field=models.CharField(default='', max_length=128, verbose_name='书名'),
        ),
    ]
