# Generated by Django 2.1.7 on 2019-07-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManager', '0003_auto_20190721_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bk_subtitle',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='副标题'),
        ),
    ]
