# Generated by Django 2.1.7 on 2019-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseLibClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, verbose_name='编码')),
                ('name', models.CharField(default='', max_length=64, verbose_name='副标题')),
                ('superior_code', models.CharField(default='', max_length=8, verbose_name='上级编码')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='状态')),
            ],
        ),
    ]
